// Import the createSlice function from the Redux Toolkit library
import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for this slice of the store
const initialState = {
    message: "Hello World",
};
// Create a slice for the 'hello' feature
const helloSlice = createSlice({
    name: "hello",
    initialState,
    // Reducers to handle actions
    // Since it's an empty object, no reducer is defined.
    // Reducers should be added here to handle different actions
    reducers: {},
});

// Export the reducer generated by the slice
// This reducer will be used to handle actions defined in the reducers object
export default helloSlice.reducer;